### ISSUE TITLE
Clean Gameday View Plugin Small Bug

### ISSUE THREAD

**Issue by Treyway995** [suchmememanyskill/Steam-Deck-Themes#27] opened 2023-04-21 12:40 UTC
Hey suchmeme, new to this github thang so please bare with me. I wanted to report a small bug with the clean gameday view plugin for steam deck. The bug is when you are in the gameday view interface and scroll down, the top bar does not always come down properly only on some occasions it does when it feels like it but not all of the time. Get back to me as soon as you can.❤️

**Comment by suchmememanyskill** [comment] 2023-04-25 14:50
This is a duplicate of #11

**Closed by suchmememanyskill** 2023-04-25 14:50 UTC
