### ISSUE TITLE
Switch Like Home not working with new Steamdeck update February 1st 2023

### ISSUE THREAD

**Issue by Shlomon-G** [suchmememanyskill/Steam-Deck-Themes#19] opened 2023-02-01 20:14 UTC
most if not all css loader themes don't seem to work anymore.

**Comment by suchmememanyskill** [comment] 2023-02-01 21:05
Duplicate of https://github.com/suchmememanyskill/SDH-CssLoader/issues/57

**Closed by suchmememanyskill** 2023-02-01 21:05 UTC
