### ISSUE TITLE
Icons disappearing when More Library Icons is enabled

### ISSUE THREAD

**Issue by alexwaddell97** [suchmememanyskill/Steam-Deck-Themes#23] opened 2023-03-22 14:27 UTC
Say I go into my Library and go to a category such as Non-Steam. with More Library Icons enabled sorted in Alphabetical view I scroll down and some of my icons are completely missing (typically the last most few). Fixes as soon as More Library Icons is disabled.

**Comment by suchmememanyskill** [comment] 2023-03-27 23:14
Duplicate of #5

**Closed by suchmememanyskill** 2023-03-27 23:14 UTC
